

#' Simulates Data from a Factor Model.
#'
#'\code{GenerateFactorData} creates a system of equations generated by observables and a latent
#'  factor system. Factors can be correlated and outcome equations can be binary or continuous.
#'  As a side effect a data set and list of variables are saved to your working directory!
#'
#' @param n the number of observations
#' @param nF the number of unobserved factors
#' @param nX the number of unobserved covariates
#' @param nM the number of continuous measures
#' @param nD the number of binary measures
#' @param sigma2.var the bounds on the uniform distribution sigma2 is drawn from
#' @param normalize a matrix of normalizations for the system (on first nF equations)
#' @param filename the stub used for outputting data and variable names
#' @param corrfactors A T/F for if factors should be generated with correlation
#' @return function returns a list holding (1) The simulated data (2) the true alphas (3) the true betas
#' @export
#' @examples
#' GenerateFactorData(n=100)
#' GenerateFactorData(n=100, nF=2, nX=3, nM=5, filename="mySim", corrfactors=F)
GenerateFactorData <- function(n=1000, nF=2, nX=5, nM=5, nD=5, sigma2.var=c(.5,4), normalize=diag(1,nF) 
                               , filename ="simulation", corrfactors=T) {
  # A function for generating factor data
  #
  # Args: n = population size | nF = number of factors | nX = number of covariates 
  #       nM = number of continuous equations | nM = number of binary equations,
  #       sigma2.var = bounds on uniform distribution sigma2 is drawm from
  #       normalize: The matrix which normalizes factor loadings
  #     corrfactors = logical for if factors ar correlated
  
  # Creating the variance and mean data i drawn from
  library("mnormt")
  Var            <- matrix(0,nF + nX, nF + nX) # variance/covariance matrix
  Var[1:nF,1:nF] <- runif(nF*nF,min = 0, max = .5)
  Var[(nF+1):(nF+nX),(nF+1):(nF+nX)] <- runif(nX*nX,min = 0, max = .3)
  diag(Var)      <- runif(nF + nX, min= 1, max = 1.1)
  for (row in 1:(nX + nF)) {
      for (col in 1:(nX + nF)) {
          if (col>row)
              Var[row,col] = Var[col,row]
          if ( (corrfactors == F & row <=nF & col <= nF & row != col ) == TRUE) {
              Var[row,col] = 0 
          }
      }
  }
  Means       <- c(rep(0,nF + nX))
  
  # Creating the data
  dta         <- rmnorm(n, mean=Means,varcov =Var )
  alpha.true  <- matrix(NA,nM + nD, nF)
  colnames(alpha.true) <- rep("alpha",nF)
  beta.true  <- matrix(NA,nM + nD, nX)
  colnames(beta.true) <- rep("beta",nX)
  alpha.true[1:nM,]  <- rnorm(nF*(nM),mean=0,sd=2)
  beta.true[1:nM,]   <- runif(nX*(nM),-3,3)
  alpha.true[(nM+1):(nM+nD),]  <- rnorm(nF*(nD),mean=0,sd=.15)
  beta.true[(nM+1):(nM+nD),]   <- rnorm(nX*(nD),mean=0,sd=.2)
  alpha.true[1:nF,1:nF] <- normalize
  sigma2.true <-        c(runif(nM,sigma2.var[1],sigma2.var[2]),rep(1,nD))
  
  # Generate my Y
  Y <-matrix(NA,n,nM + nD)
  for (iter in 1:(nM + nD) ) {
      Y[,iter]  <- dta[,(nF+1):(nF+nX)]%*% as.matrix(beta.true[iter,]) +   dta[,1:nF]%*% as.matrix(alpha.true[iter,])  + rnorm(1, mean=0, sd=sqrt(sigma2.true[iter])) 
  }
  # Replace Y for binary variables 
  for (iter in (nM+1):(nD + nM) ) {
      Y[,iter]  <- pnorm(Y[,iter]) > runif(1)
  }
  
  # col names
  ynames = list()
  for (i in 1:(nM)) ynames[[i]] <- paste("y",i,sep="")
  for (i in (nM+1):(nM +nD)) ynames[[i]] <- paste("d",i-nM, sep="")
  dtanames = list()
  for (i in (1):(nF)) dtanames[[i]] <-paste("f",i , sep="")
  for (i in (nF +1):(nF+nX)) dtanames[[i]] <-paste("x",i - nF , sep="")
  colnames(Y)   <- ynames
  colnames(dta) <- dtanames
  print(paste("Number of Observations", n))
  print(paste("Number of variables"   , dim(dta)[2]+1))
  
  simData <-data.frame(list(Y,dta))
  
  #saving files
  varnames <- as.matrix(colnames(simData))
  write.table(varnames, file = paste(filename, "_varnames.txt",sep = ""), col.names=F, row.names=F, quote=F)
  write.table(simData, file = paste(filename, "_simData.raw",sep = ""), col.names=T, row.names=F )
  return(list(simData,alpha.true,beta.true))
}
